image: node:10.22.1-alpine3.11

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - build/

install: 
  stage: install
  script:
    - CI=false npm install
  artifacts:
    expire_in: 1 hour
    paths: 
      - node_modules/

build:
  stage: build
  script: 
    - CI=false npm run build
  artifacts: 
    expire_in: 1 hour
    paths: 
      - build/

test:
  stage: test
  script:
    - CI=false npm run test

deploy:
  image: alpine
  stage: deploy

