image: node:10-alpine

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install: 
  stage: install
  script:
    - CI=false npm install
  artifacts:
    expire_in: 1 hour
    paths: 
      - node_modules/

build:
  stage: build
  script: 
    - CI=false npm run build

test:
  stage: test
  script:
    - CI=false npm run test

deploy:
  stage: deploy

