export default {
	home: '/',
	login: '/login',
	signup: '/signup',
	recover: '/recover',
	inbox: '/inbox',
	chat: '/chat',
	conversation: '/conversation',
	profile: '/profile',
	facebook: '',
	twitter: '',
	instagram: '',
	linkedIn: '',
	appStore: '',
	playStore: '',
}
