export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK'
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK'
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK'

export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE'
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE'
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE'

export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL'
export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL'
export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL'

export const SIGNUP_WITH_EMAIL = 'SIGNUP_WITH_EMAIL'
export const SIGNUP_WITH_EMAIL = 'SIGNUP_WITH_EMAIL'
export const SIGNUP_WITH_EMAIL = 'SIGNUP_WITH_EMAIL'
